---
- name: ALTERA PSK
  hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
        PSK: "{{ GPSK }}"    
    - include: tasks/login.yml
    - include: tasks/whereused.yml
    - include: tasks/alteraGTWcommunity.yml
    - include: tasks/addGTWcommunity.yml
    - include: tasks/publish.yml
    - include: tasks/logout.yml
    - include: tasks/sendmail.yml

- hosts: localhost
  gather_facts: no
  tasks: 
  - name: Atualiza CATDB
    shell: |
      echo "#!/bin/bash
      sqlplus -s "{{userdb}}/{{passdb}}@{{database}}:1521/{{database}}" <<!
      set pagesize 0;
      set echo off;
      set feedback off;
      set heading off;
      set serveroutput on size 1000000;
      set lines 1000;
      spool /tmp/ins_vp.sql;
      DECLARE
          V_SQLERRM VARCHAR2(4000);
      BEGIN
          UPDATE SYSANSIBLE.TB_VPN_AGENTES_AES256 SET PRE_SHARED_KEY=TRIM('{{ PSK }}') WHERE AGENTE_PADRONIZADO_COM_GMO=TRIM('{{ NETWORK }}');
          UPDATE SYSANSIBLE.TB_VPN_AGENTES_3DES SET PRE_SHARED_KEY=TRIM('{{ PSK }}') WHERE AGENTE_PADRONIZADO_COM_GMO=TRIM('{{ NETWORK }}');
      EXCEPTION WHEN OTHERS THEN
          V_SQLERRM := SQLERRM;
          BEGIN
              INSERT INTO SYSANSIBLE.TB_VPN_INSERT_ERRO VALUES (SYSTIMESTAMP, TRIM('{{ NETWORK }}')||V_SQLERRM);
          EXCEPTION WHEN OTHERS THEN
              INSERT INTO SYSANSIBLE.TB_VPN_INSERT_ERRO VALUES (SYSTIMESTAMP, V_SQLERRM);
          END;
      END;
      /
      COMMIT;
      spool off;
      exit;
      !" > /tmp/sql.sh
    delegate_to: "{{server_with_sqlpus_installed}}"
  
  - name: Executando sql no banco
    command: /tmp/sql.sh
    register: output
    ignore_errors: yes
    delegate_to: "{{server_with_sqlpus_installed}}"        
