---
- name: LIMPANDO IPTABLES
  hosts: WEBSERVER
  gather_facts: no
  become: yes
  become_method: sudo
  tasks: 

    - name: iptables flush filter
      iptables:
        chain: "{{ item }}"
        flush: yes
      with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

    - name: Adicionando Zabbix na lista de exceção
      iptables:
        chain: INPUT
        source: "{{zabbixSERVer}}"
        jump: ACCEPT
