---
- name: Teste adicionar comentário num alarme do MIS
  hosts: all
  gather_facts: no
  tasks: 
  - name: Acknowledge alert 
    become: false
    local_action:
      module: zabbix_ack
      server_url: "{{ server_url }}"
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      eventid: "{{ eventid }}"
      message: "Remediation attempted via Ansible Playbook"
      close_event: False
