- name: Criando a consulta no Banco
  shell: |
    echo "#!/bin/bash
    sqlplus -s "{{userdb}}/{{passdb}}@{{database}}:1521/{{database}}" <<!
    set pagesize 0;
    set echo off;
    set feedback off;
    set heading off;
    set serveroutput on size 1000000;
    set lines 1000;
    spool /tmp/ins_vp.sql;
    DECLARE
        V_SQLERRM VARCHAR2(4000);
    BEGIN
        INSERT INTO SYSANSIBLE.TB_VPN_AGENTES_AES256 VALUES
        (
             SYSANSIBLE.SEQ_TB_VPN_AGENTES_AES256.NEXTVAL
            ,TRIM('VPN_{{ NETWORK }}')
            ,TRIM('{{ NETWORK }}')
            ,TRIM('{{ NOME_EMPRESA }}')
            ,TRIM('{{ AG_CONTATO }} {{ MAIL_AGENTE }}')
            ,SYSDATE
            ,TRIM('ATIVO')
            ,TRIM('{{ AG_FW }}')
            ,TRIM('{{ PEER }}')
            ,TRIM('{{ PSK }}')
            ,TRIM('{{ NET_ID }}')
            ,TRIM('{{ IP_RANGE }}')
            ,TRIM('ITEM CRIADO VIA PROCESSO AUTOMATIZADO NO ANSIBLE')
        ); 
    EXCEPTION WHEN OTHERS THEN
        V_SQLERRM := SQLERRM;
        BEGIN
            INSERT INTO SYSANSIBLE.TB_VPN_INSERT_ERRO VALUES (SYSTIMESTAMP, 'VPN_{{ NETWORK }}'||V_SQLERRM);
        EXCEPTION WHEN OTHERS THEN
            INSERT INTO SYSANSIBLE.TB_VPN_INSERT_ERRO VALUES (SYSTIMESTAMP, V_SQLERRM);
        END;
    END;
    /
    COMMIT;
    spool off;
    exit;
    !" > /tmp/sql.sh
  delegate_to: "{{server_with_sqlpus_installed}}"

- name: Executando sql no banco
  command: /tmp/sql.sh
  register: output
  ignore_errors: yes
  delegate_to: "{{server_with_sqlpus_installed}}"
